### ISSUE TITLE
any plans to continue development on this awesome project?

### ISSUE THREAD

**Issue by kaushiknfs** [FirebrandCoding/Intergrid#1]

**Comment by Hyperseeker** [comment]
Indeed!

The project has not received any updates because I've been busy with other projects (see my repo activity). Once those are in working order – and the rest of the projects are taken care of – I'm probably going to return to Intergrid.

There's only a few bugs to fix until it's perfectly usable in its current single-column state. After that, I'm planning on overhauling the whole thing to better handle... basically everything. Not gonna be a short while, but it's going to get done eventually.

**Comment by kaushiknfs** [comment]
Few questions, out of curiosity, if i may.

- Do you eventually plan to persist the data on somewhere other than
localStorage?
- if yes, what would it be?



Kaushik

**Comment by Hyperseeker** [comment]
I'm reluctant to talk about this publicly because it's going to be nothing but talk for a while, but – yes, there's a long-term plan to also allow users to store their data on a server, so that it could be accessed from anywhere with the right link.

Intergrid was, from the very beginning, a local tool, in as much as it was related to and used by a single user. It's why I chose localStorage: it's single-user, and it's *fast*. You can [try it yourself](https://intergrid.online/): the fattest part to load is the font.

This idea also amounts to the fact that Intergrid's meant to be usable offline (not currently implemented).

Ideally, I'd have the data stored on user's drive, as a database, but this does not appear to be a possibility at the moment, at least not without an extensive set of external tools that would weigh Intergrid down in a way I'm very reluctant to approach.

If the server-side database is ever going to be a thing, it's going to be a paid one. I want to make that clear so as to not create any misconceptions. Server space costs more money than hosting an effectively-static website (all the work Intergrid currently does is on the user end, I don't have to pay for using server's CPU). The local version will always remain free.

**Comment by kaushiknfs** [comment]
Even locally, is it okay to rely on localStorage for your data? i mean, it could get lost.
Also would it scale? If i were to suppose put a large outline? store all my personal and work info on it like a PIM/ Todo List/ project management/ ... ?
Would it be easy to query when you do search?
Would it be possible to ship a sqlite db along? using probably sql.js ?

you could email me. - kaushiknfs@gmail.com

Thanks.

**Comment by Hyperseeker** [comment]
That's alright: this is a fair discussion to have in public.

> Even locally, is it okay to rely on localStorage for your data? i mean, it could get lost.

This is something I've considered for a while. Am I ready to trade whatever benefits come with using localStorage for security of user data?

I quite clearly remember myself being upset about losing sometimes gigabytes of data to an oversight or software error. It feels even worse if it's a small base of personal notes.

localStorage is the quick-and-dirty solution that works well across the board. It's easy to work with, it persists across browser sessions, and its access is immediate. Unfortunately, this persistence is imperfect at best: browsers regularly wipe older data if the system requires more disk space, or to overwrite it with newer data from other applications.

Yet, so far, this is the best option.

There is, however, a potential [persistent storage](https://developer.mozilla.org/en-US/docs/Web/API/Storage_API#Data_persistence_and_clearing) with decent support. I'm going to investigate that going forward.

Another quick-and-dirty solution – something I find acceptable while the project is yet to reach maturity – is implementing an export function. Given that the Intergrid data format is just indented plain text, you can "import" it back in my deleting the rest of the data and copy-pasting the contents of the generated `.txt` file.

And before you mention: IndexedDB is not any better in terms of persistence, though it may appear to be better at storing large amounts of structured data.

> Also would it scale? If i were to suppose put a large outline? store all my personal and work info on it like a PIM/ Todo List/ project management/ ... ?

I've just tested this with my own notes of 5000+ elements. It came out to 621kB, all successfully stored and represented on reload.

[Data is incluclusive](https://stackoverflow.com/a/2989317) as to how much one can actually store in localStorage. Some say it's safe for up to 5MB.

The biggest problem with having so many elements in the Intergrid notes is a significant lag on every operation. This is obviously undesirable, but it is a consequence of the current architecture that relies on DOM a lot.

> Would it be easy to query when you do search?

Filtering isn't yet implemented, so there's no conclusive way to say one way or another.

> Would it be possible to ship a sqlite db along? using probably sql.js ?

Like I said, I would if I could. Having a stable database along would be great. Sadly, [the only potential browser API for that](https://developer.mozilla.org/en-US/docs/Web/API/File_and_Directory_Entries_API) is neither supported by all evergreen browsers nor is standard.

And just so you're aware: SQL.js does not provide one with a way to store such data. At best, it requires a server to read from and store to. At its core, it's not much more than a session-based TypedArray manager. It can *export* databases, and it can *read* them if provided by user (who'd have to open it like a regular file), but it's no nearly as powerful as its nature might suggest.

If you have suggestions as to how to handle data storage better, I'm eager to listen: I'm always looking for ways to improve the software.

**Comment by Hyperseeker** [comment]
I'm going to close this one, since the issue seems to have exhausted itself. The project is going to continue eventually.
